swagger: '2.0'
info:
 title: 模型仿真评估工具接口文档（BaseURL:192.168.9.64:8888/model-assessment）
 description: 模型仿真评估工具接API文档。新的标准规范：所有单参数存放多个数据的一律使用json.dumps进行转换，比如列表或者字典，接收端使用json.loads获取原始结构。为了提升速度和便捷性，模糊查找一律返回对应列的完整信息，由前端决定是否使用其他信息，由于模糊查找的列可能允许重名，因此是否使用对应的ID需要由前端决定并确保准确性
 version: 1.0.0
host: 192.168.9.64:8888
schemes:
 - http
basePath: /model-assessment
tags:
 - name: Model Simulate Assessment
   description: 模型仿真评估工具接口文档
paths:
 /model-assessment:
   get:
     tags:
       -
     summary: 获取所有消息实例和对应的消息详情信息
     consumes:
       - multipart/form-data
     operationId: getAllMessageInfoUsingGET
     produces:
       - '*/*'
     parameters:
       - name: pageNum
         in: query
         description: 显示第几页
         required: false
         type: integer
       - name: pageSize
         in: query
         description: 每页大小
         required: false
         type: integer
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
   post:
     tags:
       - Message Manager
     summary: 创建新的消息通知
     description: 创建新的消息，并且同时创建用户消息实例
     operationId: createNewMessageExampleUsingPOST
     consumes:
       - application/json
     produces:
       - '*/*'
     parameters:
       - in: body
         name: messageInfo
         description: 消息信息实体类对象，通知标题、通知具体内容、通知等级必传、创建消息用户、消息失效时间必传，目标用户ID与目标用户必须选择一个传入
         required: true
         schema:
           $ref: '#/definitions/MessageInfo'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '201':
         description: Created
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
   put:
     tags:
       - Message Manager
     summary: 更新通知以及通知实例
     description: 根据消息Id更新消息通知
     operationId: updateMessageByMessageIdUsingPUT
     consumes:
       - application/json
     produces:
       - '*/*'
     parameters:
       - in: body
         name: messageInfo
         description: 要更新的消息内容，封装为消息实体类对象
         required: true
         schema:
           $ref: '#/definitions/MessageInfo'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '201':
         description: Created
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
   delete:
     tags:
       - Message Manager
     summary: 根据ID删除多个消息实例
     description: 根据Id删除消息信息，同时删除对应通知实例(支持单个删除)
     operationId: removeManyMessageExampleUsingDELETE
     produces:
       - '*/*'
     parameters:
       - in: body
         name: paramsArr
         description: 要删除的消息的ID数组
         required: true
         schema:
           $ref: '#/definitions/ArrParams'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '204':
         description: No Content
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
     deprecated: false
 /airmessage/message/instance/user/current:
   get:
     tags:
       - Message Manager
     summary: 获取当前用户的所有消息实例
     operationId: getUserAllExampleByIdUsingGET
     produces:
       - '*/*'
     parameters:
       - in: body
         description: 分页请求信息：其中分页属性、当前用户id必须添加，筛选条件自选
         required: true
         name: params
         schema:
           $ref: '#/definitions/SearchParams'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
 /airmessage/message/instance/user/current/latest:
   get:
     tags:
       - Message Manager
     summary: 获取当前用户的所有最新未读实例，给出一个固定数量的显示
     operationId: getUserUnreadExampleUsingGET
     produces:
       - '*/*'
     parameters:
       - in: body
         description: 请求信息：当前用户id必须添加，筛选条件自选
         name: params
         required: true
         schema:
           $ref: '#/definitions/SearchParams'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
 '/airmessage/message/instance/user/{userId}':
   get:
     tags:
       - Message Manager
     summary: 获取指定用户的所有消息实例
     consumes:
       - multipart/form-data
     operationId: getUserAllExampleByIdUsingGET_1
     produces:
       - '*/*'
     parameters:
       - in: path
         description: 指定的用户id
         name: userId
         required: true
         type: integer
       - in: body
         name: params
         description: 分页请求信息：其中分页属性、指定用户id必须添加，筛选条件自选
         required: true
         schema:
           $ref: '#/definitions/SearchParams'
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
 '/airmessage/message/instance/{instance_id}':
   put:
     tags:
       - Message Manager
     summary: 根据实例ID更新实例状态
     operationId: updateInstanceStatusUsingPUT
     consumes:
       - application/json
     produces:
       - '*/*'
     parameters:
       - name: instanceId
         in: path
         description: 要更新的实例Id
         required: true
         type: integer
       - name: instance_id
         in: path
         description: instance_id
         required: true
         type: integer
         format: int32
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '201':
         description: Created
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
   delete:
     tags:
       - Message Manager
     summary: 根据实例ID删除实例
     operationId: removeInstanceByIdUsingDELETE
     produces:
       - '*/*'
     parameters:
       - name: instanceId
         in: path
         description: 要删除的实例Id
         required: true
         type: integer
       - name: instance_id
         in: path
         description: instance_id
         required: true
         type: integer
         format: int32
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '204':
         description: No Content
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
     deprecated: false
 /airmessage/message/statis:
   get:
     tags:
       - Message Manager
     summary: 获取所有消息统计信息
     description: 统计每个消息的：通知等级、类型、阅读情况等
     consumes:
       - multipart/form-data
     operationId: getAllMessageInfoStatisUsingGET
     produces:
       - '*/*'
     parameters:
       - name: userId
         in: formData
         description: 当前用户ID
         required: false
         type: integer
       - name: userName
         in: formData
         description: 当前用户名称
         required: false
         type: string
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
 '/airmessage/message/{messageId}':
   get:
     tags:
       - Message Manager
     summary: 根据消息Id获取消息详细信息
     operationId: getMessageInfoByIdUsingGET
     produces:
       - '*/*'
     parameters:
       - name: messageId
         in: path
         description: 要获取的消息Id
         required: true
         type: integer
     responses:
       '200':
         description: 请求码，成功
         schema:
           $ref: '#/definitions/ResponseBody'
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not Found
     deprecated: false
definitions:
 ArrParams:
   type: integer
   properties:
     paramsArr:
       type: array
       format: int32
 JSONObject:
   type: object
   title: JSONObject
   additionalProperties:
     type: object
 ResponseBody:
   type: object
   properties:
     code:
       type: string
     data:
       type: array
       items:
         type: object
     message:
       type: string
   title: ResponseBody
 Timestamp:
   type: object
   properties:
     date:
       type: integer
       format: int32
     day:
       type: integer
       format: int32
     hours:
       type: integer
       format: int32
     minutes:
       type: integer
       format: int32
     month:
       type: integer
       format: int32
     nanos:
       type: integer
       format: int32
     seconds:
       type: integer
       format: int32
     time:
       type: integer
       format: int64
     timezoneOffset:
       type: integer
       format: int32
     year:
       type: integer
       format: int32
   title: Timestamp
 SearchParams:
   type: object
   required:
     - pageNum
     - pageSize
   properties:
     id:
       type: integer
       format: int32
       description: 对应各种传入的ID
     notification_level:
       type: integer
       format: int32
       description: 筛选属性：通知级别
     notification_title:
       type: string
       description: 筛选属性：通知标题
     notification_type:
       type: integer
       format: int32
       description: 筛选属性：通知类型
     pageNum:
       type: integer
       format: int32
       description: 分页属性：当前页
     pageSize:
       type: integer
       format: int32
       description: 分页属性：每页显示数据条数
     service_id:
       type: integer
       format: int32
       description: 筛选属性：服务ID
     showNum:
       type: integer
       format: int32
       description: 显示用户固定数量未读实例时，限制显示数量
     source_user_id:
       type: integer
       format: int32
       description: 筛选属性：创建通知用户ID
     userId:
       type: integer
       format: int32
       description: 用户ID
     userName:
       type: string
       description: 用户名字
   title: 搜索参数实体类
 MessageInfo:
   type: object
   required:
     - invalidatedTime
     - notificationContent
     - notificationLevel
     - notificationTitle
     - notificationType
     - serviceId
     - sourceUserId
   properties:
     invalidatedTime:
       description: 通知有效时间
     notificationContent:
       type: string
       description: 通知内容
     notificationLevel:
       type: integer
       format: int32
       description: 通知级别
     notificationTitle:
       type: string
     notificationType:
       type: string
       description: 通知类型
     serviceId:
       type: integer
       format: int32
       description: 服务ID
     sourceUserId:
       type: integer
       format: int32
       description: 创建该消息的用户ID
     targetUserId:
       type: integer
       format: int32
       description: 通知目标用户ID
     targetUserLevel:
       type: string
       description: 通知目标用户级别

   title: 通知消息实体类